"""Adicionando relacionamento entre Consulta e Paciente

Revision ID: 3baba6eefc7b
Revises: 
Create Date: 2024-10-05 21:03:05.006473

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3baba6eefc7b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('paciente', schema=None) as batch_op:
        batch_op.alter_column('telefone',
               existing_type=sa.VARCHAR(length=15),
               nullable=False)
        batch_op.alter_column('endereco',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('paciente', schema=None) as batch_op:
        batch_op.alter_column('endereco',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
        batch_op.alter_column('telefone',
               existing_type=sa.VARCHAR(length=15),
               nullable=True)

    # ### end Alembic commands ###
